image: openjdk:8-jdk

variables:
  tomcat_dir: D:\tomcat\apache-tomcat-8.0.36

stages:
  - build
  - test

before_script:
  - chmod u+x ./mvnw

build:
  stage: build
  script:
    - ./mvnw compile
    - ./mvnw war:exploded
  artifacts:
    paths:
      - target/base
  tags:
    - package

deploy-test:
  stage: test
  script:
    - echo stop tomcat server...
    - Stop-Service Tomcat8
    - echo remove old artifacts...
    - echo copy new artifacts...
    - echo start tomcat server...
    - Start-Service Tomcat8
  dependencies:
    - build
  tags:
    - test
