image: openjdk:8-jdk

variables:
  tomcat_dir: D:\tomcat\apache-tomcat-8.0.36

stages:
  - build
  - test

before_script:
  - chmod u+x ./mvnw

build:
  stage: build
  script:
    - ./mvnw compile
    - ./mvnw war:exploded
  artifacts:
    paths:
      - target/base
  tags:
    - package

deploy-test:
  stage: test
  script:
    - ls target
    - cd ${tomcat_dir}\bin && .\shutdown.bat
    - rm -rf ${tomcat_dir}\webapps\base
    - cp -r target\base ${tomcat_dir}\webapps
    - cd ${tomcat_dir}\bin && .\startup.bat
  dependencies:
    - build
  tags:
    - test
