image: openjdk:8-jdk

stages:
  - build
  - test
  - production

build:
  stage: build
  script:
    - chmod u+x ./mvnw
    - ./mvnw compile
    - ./mvnw war:exploded
  artifacts:
    paths:
      - target/base
  tags:
    - package

deploy-test:
  stage: test
  variables:
    tomcat_dir: D:\java_doc\apache-tomcat-8.0.36
    service_name: 8.0.36
  script:
    - echo -n "stop tomcat server..."
    - Stop-Service ${service_name}
    - echo -n "remove old artifacts..."
    - if (Test-Path ${tomcat_dir}\webapps\base) {rm -r ${tomcat_dir}\webapps\base}
    - echo -n "copy new artifacts..."
    - cp -r target\base ${tomcat_dir}\webapps
    - mv ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.example ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.properties
    - echo -n "start tomcat server..."
    - Start-Service ${service_name}
  dependencies:
    - build
  when: manual
  tags:
    - test

deploy-production-east:
  stage: production
  variables:
    tomcat_dir: D:\java_doc\apache-tomcat-8.0.36
    service_name: 8.0.36
  script:
    - echo -n "stop tomcat server..."
    - Stop-Service ${service_name}
    - echo -n "remove old artifacts..."
    - if (Test-Path ${tomcat_dir}\webapps\base) {rm -r ${tomcat_dir}\webapps\base}
    - echo -n "copy new artifacts..."
    - cp -r target\base ${tomcat_dir}\webapps
    - mv ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.example ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.properties
    - echo -n "start tomcat server..."
    - Start-Service ${service_name}
  dependencies:
    - build
    - deploy-test
  when: manual
  tags:
    - production
  only:
    refs:
      - master

deploy-production-west:
  stage: production
  variables:
    tomcat_dir: D:\java_doc\apache-tomcat-8.0.36
    service_name: 8.0.36
  script:
    - echo -n "stop tomcat server..."
    - Stop-Service ${service_name}
    - echo -n "remove old artifacts..."
    - if (Test-Path ${tomcat_dir}\webapps\base) {rm -r ${tomcat_dir}\webapps\base}
    - echo -n "copy new artifacts..."
    - cp -r target\base ${tomcat_dir}\webapps
    - mv ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.example ${tomcat_dir}\webapps\base\WEB-INF\classes\config\dbparam.properties
    - echo -n "start tomcat server..."
    - Start-Service ${service_name}
  dependencies:
    - build
    - deploy-test
  when: manual
  tags:
    - production
  only:
    refs:
      - master
