image: openjdk:8-jdk

stages:
  - build
  - deploy

before_script:
  - chmod u+x ./mvnw

build:
  stage: build
  script:
    - ./mvnw compile
    - ./mvnw war:exploded
  artifacts:
    paths:
      - target/base
  tags:
    - package

deploy:
  stage: deploy
  script:
    - ls
  dependencies:
    - build
  tags:
    - deploy
