image: openjdk:8-jdk

stages:
  - build
  - test

before_script:
  - chmod u+x ./mvnw

build:
  stage: build
  script:
    - ./mvnw compile
    - ./mvnw war:exploded
  artifacts:
    paths:
      - target/base
  tags:
    - package

deploy-test:
  stage: test
  script:
    - ls target
    - cd D:\tomcat\apache-tomcat-8.0.36\bin
    - .\shutdown.bat
    - cd ../webapps
    - rm -r base
    - cd ${CI_BUILDS_DIR}
    - cp -r target\base D:\tomcat\apache-tomcat-8.0.36\webapps
    - cd D:\tomcat\apache-tomcat-8.0.36\bin
    - .\startup.bat
  dependencies:
    - build
  tags:
    - test
